# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 22032087
  contracts:
  - name: PendleVotingController
    address:
    - 0x44087E105137a5095c008AaB6a6530182821F2F0
    handler: src/EventHandlers.ts
    events:
    - event: Vote(address indexed user, address indexed pool, uint64 weight, (uint128,uint128) vote)
      field_selection:
        transaction_fields:
          - hash
  - name: VePendle
    address:
    - 0x4f30A9D41B80ecC5B94306AB4364951AE3170210
    handler: src/VePendleHandlers.ts
    events:
    - event: NewLockPosition(address indexed user, uint128 amount, uint128 expiry)
